name: Code formatter with Prettier

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Formatter: Prettier for css, HTML and yml files
      - name: Install prettier
        run: npm install prettier --global

      - name: Format code with Prettier
        run: prettier . --write
