name: Code formatter with Prettier

on:
  push:
    branches: ["main"]
    
permissions: write-all

jobs:
  run-lint:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_CHECKOV: false
          FIX_JAVASCRIPT_PRETTIER: true
          FIX_JAVASCRIPT_STANDARD: true
          FIX_YAML_PRETTIER: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit and push linting fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        run: cat ./test.js
