---
name: Lint

on: # yamllint disable-line rule:truthy
  pull_request: null

permissions:
  contents: read

jobs:
    # Super-linter workflow running in check only mode
    # See https://github.com/super-linter/super-linter#get-started

  fix-lint-issues:
    permissions:
      # To write linting fixes
      contents: write
      # To write Super-linter status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache Docker image
      - name: Cache Docker image
        uses: actions/cache@v4.2.0
        with:
          path: /tmp/.docker-cache
          key: super-linter-cache-${{ runner.os }}-${{ hashFiles('super-linter.yml', '**/*.js', '**/*.json') }}
          restore-keys: |
            super-linter-cache-${{ runner.os }}-

      - name: Super-Linter
        uses: super-linter/super-linter/slim@v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          FIX_JAVASCRIPT_PRETTIER: true  # Nur JavaScript mit Prettier fixen
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_STANDARD: false  # Deaktiviere `JAVASCRIPT_STANDARD`

      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests
        # - Not on the default branch
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
